# Generated by Django 5.0 on 2023-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_one', models.CharField(max_length=250, verbose_name='Название')),
                ('a_two', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('a_three', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_one', models.CharField(max_length=250, verbose_name='Название')),
                ('a_two', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('a_three', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='ModelC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_one', models.CharField(max_length=250, verbose_name='Название')),
                ('a_two', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('a_three', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
    ]
